### ISSUE TITLE
What's the purpose/difference

### ISSUE THREAD

**Issue by vladshcherbin** [matt-allan/rollup-plugin-terser#1]
Hey,

there is already a [rollup-plugin-terser](https://github.com/TrySound/rollup-plugin-terser), what's the purpose/difference of this package?

**Comment by matt-allan** [comment]
Hi,

This project aims to provide a minimal wrapper for Terser so it can be used with rollup. It doesn't provide any features that aren't provided by terser itself.

The existing package adds parallelization and runs each chunk in it's own worker.  It also adds some pretty printing for errors.  To provide the extra functionality it pulls in [29 packages](http://npm.anvaka.com/#/view/2d/rollup-plugin-terser).  It will likely be faster on a large project that uses code splitting.

I didn't need that functionality and I preferred having fewer dependencies so I wrote my own.  This package does not include any functionality that isn't available in terser and has no dependencies except for terser itself.

Looking at the code there are some other minor differences.  The existing package looks like it only raises errors; this package raises warnings too.  The existing package evals the options object in the worker's scope, while this package will pass the options directly to terser in the current scope.

**Comment by vladshcherbin** [comment]
@yuloh nice, thank you for detailed explanation :)
